# Generated by Django 6.0.4 on 2026-04-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('sim_swap', 'SIM Swap'), ('device_status', 'Device Status'), ('number_verification', 'Number Verification'), ('location_verification', 'Location Verification')], max_length=50)),
                ('provider', models.CharField(default='CAMARA', max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telecom_checks', to='transactions.transaction')),
            ],
        ),
    ]
