# Generated by Django 6.0.4 on 2026-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcheck',
            name='reference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcheck',
            name='check_type',
            field=models.CharField(choices=[('number_verification', 'Number Verification'), ('sim_swap', 'SIM Swap'), ('device_swap', 'Device Swap'), ('location_verification', 'Location Verification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='telecomcheck',
            name='provider',
            field=models.CharField(default='CAMARA_MOCK', max_length=100),
        ),
    ]
