# Generated by Django 6.0.4 on 2026-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0002_telecomcheck_reference_alter_telecomcheck_check_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcheck',
            name='check_type',
            field=models.CharField(choices=[('number_verification', 'Number Verification'), ('sim_swap', 'SIM Swap'), ('device_swap', 'Device Swap'), ('location_verification', 'Location Verification'), ('kyc_match', 'KYC Match'), ('kyc_tenure', 'KYC Tenure')], max_length=50),
        ),
    ]
