# Generated by Django 6.0.4 on 2026-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='api_key',
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('fintech', 'Fintech'), ('mno', 'Mobile Network Operator'), ('bank', 'Bank'), ('merchant', 'Merchant')], default='fintech', max_length=50),
        ),
    ]
